# Generated by Django 3.1.3 on 2020-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='retreat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='retreat',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='retreat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
