# Generated by Django 3.1.3 on 2020-12-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0002_auto_20201223_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
